version: "3.9"
services:
  client1:
    image: opencda
    network_mode: host
    environment:
      CLIENT_ORDER: "4"
      CLIENT_NUMBER: "6"
  client2:
    image: opencda
    network_mode: host
    environment:
      CLIENT_ORDER: "5"
      CLIENT_NUMBER: "6"  
  client3:
    image: opencda
    network_mode: host
    environment:
      CLIENT_ORDER: "6"
      CLIENT_NUMBER: "6"
